#!/usr/bin/env python3

## notashark - discord bot for King Arthur's Gold
## Copyright (c) 2021 moonburnt
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program.  If not, see https://www.gnu.org/licenses/gpl-3.0.txt

from notashark import discord_bot
from os import environ
from sys import exit
import logging

BOT_NAME = "notashark"
DEFAULT_LOGGING_LEVEL = logging.INFO
DEFAULT_STATISTICS_UPDATE_TIME = 10

try:
    LOGGING_ENVAR = str(environ['SCRIPT_LOGGING_LEVEL'].lower())
except:
    LOGGING_LEVEL = DEFAULT_LOGGING_LEVEL
else:
    if LOGGING_ENVAR == "debug":
        LOGGING_LEVEL = logging.DEBUG
    elif LOGGING_ENVAR == "warning":
        LOGGING_LEVEL = logging.WARNING
    else:
        LOGGING_LEVEL = logging.INFO

log = logging.getLogger()
log.setLevel(LOGGING_LEVEL)
handler = logging.StreamHandler()
handler.setFormatter(logging.Formatter(fmt='[%(asctime)s][%(name)s][%(levelname)s] %(message)s', datefmt='%d.%m.%y %H:%M:%S'))
log.addHandler(handler)

log.info(f'Logging level has been set to "{LOGGING_LEVEL}"')

try:
    BOT_TOKEN = environ['DISCORD_KEY']
except KeyError:
    log.critical("DISCORD_KEY environment variable isnt set. Edit bootin_up.sh accordingly, or set it up manually.\nAbort")
    exit(1)

#to be removed and replaced with json-driven settings file configurable from within discord
# try:
    # STATISTICS_CHANNEL_ID = int(environ['STATISTICS_CHANNEL_ID'])
# except:
    # log.warning("STATISTICS_CHANNEL_ID isnt set, server stats wont be gathered")
    # STATISTICS_CHANNEL_ID = None
# else:
    # log.info(f"STATISTICS_CHANNEL_ID has been set to {STATISTICS_CHANNEL_ID}")

try:
    STATISTICS_UPDATE_TIME=int(environ['STATISTICS_UPDATE_TIME'])
except:
    log.warning("STATISTICS_UPDATE_TIME isnt set, using defaults instead")
    STATISTICS_UPDATE_TIME = 30
else:
    if STATISTICS_UPDATE_TIME < DEFAULT_STATISTICS_UPDATE_TIME:
        STATISTICS_UPDATE_TIME = DEFAULT_STATISTICS_UPDATE_TIME
log.info(f"STATISTICS_UPDATE_TIME has been set to {STATISTICS_UPDATE_TIME} seconds")

discord_bot.main(BOT_TOKEN, BOT_NAME, STATISTICS_UPDATE_TIME)
